### ISSUE TITLE
Support static type checker

### ISSUE THREAD

**Issue by ramonhagenaars** [ramonhagenaars/nptyping#34] opened 2020-09-05 17:53 UTC
An often asked question is whether `nptyping` supports a static type checker such as `mypy`, which at the moment isn't the case. Implementing this feature will be difficult (if even possible for some type checkers).

Here is an example of a challenge:
```python
import numpy as np
import nptyping as npt

arr2x2: npt.NDArray[(2, 2), int] = np.array([[1, 2], [3, 4]])
arr4: npt.NDArray[4, int] = np.reshape(arr2x2, 4)  # How is nptyping supposed to reassure that the type is correct (with no influence on np.reshape)?
```

There are several type checkers available such as `mypy`, `pyright`, `pyre-check`, `pytype`. Some support plugins (e.g. `mypy`) which may be something to look into.

The most widely used type checker would be `mypy`, so it would seem reasonable to start with that particular one.

**Comment by hallmeier** [comment] 2020-09-07 16:45
When type hinting in PyCharm with `NDArray` and using that function, I run into the annoying warning

> Expected type 'NDArray', got 'ndarray' instead

I don't expect the shape of the array to be statically checked, but could `NDArray` be made a subclass of `numpy.ndarray`, so that `ndarray`s are accepted in functions type hinting an `NDArray`?

I get the same warning when using `typish.instance_of(x, List[str])` since `GenericAlias` is no subclass of `type`.

**Comment by ramonhagenaars** [comment] 2020-09-07 17:17
> could NDArray be made a subclass of numpy.ndarray, so that ndarrays are accepted in functions type hinting an NDArray?

[`NDArray` already is a `numpy.ndarray`](https://github.com/ramonhagenaars/nptyping/blob/master/nptyping/types/_ndarray.py).

> I get the same warning when using typish.instance_of(x, List[str]) since GenericAlias is no subclass of type.

Would you please open an issue in the [`typish project`](https://github.com/ramonhagenaars/typish/issues) for that?

**Comment by hallmeier** [comment] 2020-09-08 09:34
Ah right, it would have to be the other way around. `numpy.ndarray` would have to be a subclass of `NDArray` to be accepted in function type hinting an `NDArray`. Or something of the magic that makes the aliases in `typish` work could be applied here?

**Comment by baterflyrity** [comment] 2020-09-29 12:04
Awesome package! But I receive tons of warnings like `NDArray is not ndarray` in PyCharm. Does someone know how to solve this issue?

**Comment by ramonhagenaars** [comment] 2020-10-03 16:40
Maybe with PyCharm plugins? I have 0 experience on that topic though...

**Comment by baterflyrity** [comment] 2020-10-03 17:11
> Maybe with PyCharm plugins? I have 0 experience on that topic though...

Just pytypechecker in pycharm does not recognize NDArray as numpy.ndarray. Guess someone should include *only dynamic checks are available* in readme.

**Comment by vkhodygo** [comment] 2021-03-04 17:20
@ramonhagenaars Does it mean all PyCharm errors related to isinstance are related to this issue and are effectively invalid?

**Comment by ramonhagenaars** [comment] 2021-03-14 12:46
> @ramonhagenaars Does it mean all PyCharm errors related to isinstance are related to this issue and are effectively invalid?

Unfortunately yes. I can imagine that it would be possible to write some kind of PyCharm plugin. Same with static type checkers. If anyone is reading this with experience with that, I'd be glad to hear it.

**Comment by BvB93** [comment] 2021-05-14 12:00
While not the most satisfying solution, one possibility would be to type `NDArray` as `Any` while static type checking:

``` python
from typing import TYPE_CHECKING, Any

# NOTE: This will disable all type safety while static type checking
if TYPE_CHECKING:
    NDArray: Any
else:
    class NDArray(_NDArray, np.ndarray):
        pass  # Insert implementation details
```
Better results could be achieved by aliasing it as `NDArray = np.ndarray`, rather than `NDArray: Any`. 
This would mean that you'd somehow have to get rid of all `__getitem__` parameters though (which I'm not sure how to do), 
lest type checkers will keep spitting out errors.

**Comment by leycec** [comment] 2021-08-05 21:31
**2021 Q3 heads up:** [NumPy ≥ 1.20.0 has begun providing official type-hinting support via the new `numpy.typing` subpackage and, in particular, the new `numpy.typing.NDArray` type-hinting factory](https://numpy.org/devdocs/reference/typing.html#numpy.typing.mypy_plugin.NDArray).

It'd be awesome if `nptyping` could somehow unify its efforts with NumPy's, which would also go a long way to resolving this project's lingering incompatibility with static analysis checkers like mypy and PyCharm. Thanks for all the ongoing inspiration, @ramonhagenaars!

**Comment by ShayHill** [comment] 2021-09-28 12:38
The Pycharm "Expected type 'NDArray', got 'ndarray' instead" issue is ugly. FWIW, there's an ugly-er workaround:

```
def func() -> nptyping.NDArray[(3,), int]:
    # warns "Expected type 'NDArray', got 'ndarray' instead"
    return np.array([0, 1, 2])

def func_times_1() -> nptyping.NDArray[(3,), int]:
    # no warning
    return np.array([0, 1, 2]) * 1
```

**Comment by sarimmehdi** [comment] 2021-12-27 20:36
@ShayHill why is the second function not giving a warning?

**Comment by ShayHill** [comment] 2021-12-27 22:54
@sarimmehdi , Pycharm will recognize the type when I add * 1. No idea why, but it works.

**Comment by Jasha10** [comment] 2021-12-27 22:56
It might be that `np.array([0, 1, 2]) * 1` is being typed as `Any`.

**Comment by bskinn** [comment] 2022-01-21 16:36
Re-reading my commit message, I want to clarify that I recognize that the lack of typing support isn't due to any negligence here! It's a challenging problem, for which a solution just hasn't been found yet.

**Comment by matanster** [comment] 2022-02-05 21:13
@leycec I don't really see numpy's typing addition to allow typing by array dimensions, but maybe I am wrong. It seems that [beartype provides a solution to this through its lambda feature though](https://github.com/beartype/beartype#beartype-validators). Happy to learn if I am missing something. 

Like other people mentioned, I think that having warnings in PyCharm which stem from its unawareness to nptyping do go against the cognitive value of type annotations a lot.

**Comment by leycec** [comment] 2022-02-05 23:41
> I don't really see numpy's typing addition to allow typing by array dimensions very directly...

**Nope.** You're *absolutely* correct. The lack of dimensionality constraints is an unresolved pain point throughout the NumPy QA subcommunity (i.e., us). `nptyping` still very much has the computational leg up here – especially by compare to the official `numpy.typing` subpackage.

> ...having warnings in PyCharm which stem from its unawareness to `nptyping` do go against the cognitive value of type annotations a lot.

**Yup.** Again, you're *absolutely* correct. In theory, `nptyping` could entirely mitigate this unique pain point by embracing [PEP 593 -- Flexible function and variable annotations](https://www.python.org/dev/peps/pep-0593). Doing so would render your type hints PEP-compliant and thus implicitly supported across Python's type-hinting ecosystem – including by both mypy and Pycharm. In practice, this would (perhaps unacceptably) increase the verbosity of your type hints. Beartype validators gladly accepted this tradeoff, because PEP-compliance >>>>>>>> verbosity.

`nptyping` type hints turbocharged by PEP 593 might then look like:

``` python
from numpy import ndarray
from nptyping import NDArray
from typing import Annotated

# Is this dark magic? This is nptyping 2.0.
NDArrayNDim1 = Annotated[ndarray, NDArray[(typing.Any,), typing.Any]]
```

API food for thought. In any case, thanks again for all the tremendous volunteerism here and elsewhere, everyone! :fireworks:

**Comment by baterflyrity** [comment] 2022-02-06 10:29
@leycec 
Tell me please whether this code is working or just predictions. If the deal is in implementing `NDArray.__call__` method then it will be very good.
 
```python
from numpy import ndarray
from nptyping import NDArray
from typing import Annotated

# Is this dark magic? This is nptyping 2.0.
NDArrayNDim1 = Annotated[ndarray, NDArray[(typing.Any,), typing.Any]]```

**Comment by leycec** [comment] 2022-02-06 23:55
Why, it's... both! :smile: :disappointed: 

It's **just working** in the sense that `typing.Annotated` supports all possible objects. You can stuff literally anything into `typing.Annotated` – including beartype validators (in our case) or `nptyping.NDArray` types (in yours). That was sorta the whole reason for PEP 593's existence, after all: to enable all us non-CPython QA devs outside the formal PEP standardization process to still design and publish PEP-compliant type hints.

It's **just predictions** in the sense that everyone else will currently reduce `Annotated[ndarray, NDArray[...]]` type hints to the `numpy.ndarray` class by selectively ignoring the `NDArray[...]` constraints. Type-checking those hints in full by applying the `NDArray[...]` constraints will require *every* runtime and static type checker to individually add specific support for those constraints – I think, anyway. But maybe an official `nptyping` dev with a better understanding of the `nptyping` API can weigh in here.

So, good news and bad news. I'd say that's still an improvement over the current situation of `nptying` being incompatible with increasingly popular static type checkers and IDEs. That's *not* a place you want to be, really.

**Comment by ramonhagenaars** [comment] 2022-02-07 21:33
Great to see this discussion has really taken of with some very interesting ideas and suggestions! 💪 

I agree that Pycharm- and MyPy-friendlier hinting should be on top of nptypings agenda. And it is!

Some time has passed since my initial efforts to bring typing to Numpy. I have been experimenting myself and tried all my (limited) black magic to make nptyping Pycharm-MyPy-approved, without sacrificing on the style. And I failed. 😆 

The latest suggestions done by @leycec seem very promising to me though. 🥇 

---

Currently, the best I can come up with is the following:

1. the `numpy.typing.NDArray` will be wrapped inside `Annotated`. This is to be done by the users of nptyping, although helper functions can be made later on;
2. A class `Dim` will be added that takes arguments to denote the dimension(s) of an array;
3. A separate function will be added (e.g. `is_instance_of`) to do the dynamic instance checking of a numpy array against the hint.

Defining an array hint would fall down to the following:
```python
Array<DIMENSIONSPEC> = Annotated[NDArray[T], Dim(<DIMENSION ARGS>)]
```
`<DIMENSIONSPEC>` would be the part of the type name that denotes the dimensions of the array
`<DIMENSION ARGS>` would be the arguments that `Dim` takes to allow for instance-checking
`NDArray` comes from numpy here, not nptyping.
 
Here are some examples:
```python
# 1 dimension of any size
ArrayN = Annotated[NDArray[T], Dim(Any)]

# 1 dimension of size 3
Array3 = Annotated[NDArray[T], Dim(3)]

# 3 dimensions of size 3, 3 and any
Array3x3xN = Annotated[NDArray[T], Dim(3, 3, Any)]

# n dimensions of size 3
Array3n = Annotated[NDArray[T], Dim(3, ...)]

# Any dimensions of any size
Array = Annotated[NDArray[T], Dim(Any, ...)]
# (or just np.ndarray or np.NDArray)

```
Again, the code above resides in the user's codebase, not nptyping's, because nptyping cannot possibly offer all potential combinations of dimensions. A function to help with these names _can_ be offered though. something like `suggest_name(Dim(3, ...))`.

These type hints can then be used as follows:
```python
def fun(arr: Array3[Float]) -> Array3x3xN[Float]:
    arr.dtype                                  # PyCharm does code completion!
    assert is_instance_of(arr, Array3[Float])  # nptyping will dynamically check this
    return arr                                 # PyCharm and MyPy will NOT detect the issue with this


fun(np.array([1., 2., 3.]))                    # PyCharm is happy, MyPy is happy
fun("not-an-array")                            # Both PyCharm and MyPy complain
```

What do you guys think?

**Comment by leycec** [comment] 2022-02-08 07:41
**Yup.** That's raw steaming hotness. As @beartype guy, I have only two pertinent comments:

> ...the `numpy.typing.NDArray` will be wrapped inside `Annotated`. This is to be done by the users of `nptyping`, although helper functions can be made later on;

This is all fantabulous – *except* possibly that trailing proviso about helper functions. On the one hand, helper functions are helpful. That's good. On the other hand, static type checkers and IDEs are utterly incapable of understanding helper functions defined at runtime. That's bad.

Although you could certainly go ahead and publish those helper functions, doing so would also render downstream code calling those helper functions uncheckable by static type checkers. That means errors and warnings for your userbase. And... you're kinda back to square one there. :grimacing: 

Because the static type checkers that dominate Python type-checking are ~~fundamentally deficient~~ less intelligent than desired, all the *rest* of us who may not necessarily care about static type-checking are nonetheless constrained to pander to the lowest-common denominator. Which means mypy. Always mypy, folks.

This means you can't really do much to simplify the core syntax for type hints. You can't reliably create concise factory functions that generate type hints on behalf of your users. Instead, as grotesque as `typing.Annotated` admittedly is, it's the best we've got.

Okay, it's *all* we've got. :smiling_face_with_tear: 

> A separate function will be added (e.g. `is_instance_of`) to do the dynamic instance checking of a numpy array against the hint.

**Absolutely feasible.** Alternatively, if you'd prefer to offload the work to @beartype, `beartype 0.10.0` introduces a similar `is_bearable()` function. It's a supercharged analogue to the `isinstance()` builtin except supporting *everything* supported by @beartype. So, basically everything: e.g.,

``` python
>>> from beartype.abby import is_bearable
>>> is_bearable(['Things', 'fall', 'apart;'], list[str])
True
>>> is_bearable(['the', 'centre', 'cannot', 'hold;'], list[int])
False
```

Assuming @beartype adds support for your proposed `nptyping.Dim` type, `is_bearable()` would then transparently support that type as well: e.g.,

``` python
from beartype.abby import is_bearable

def fun(arr: Array3[Float]) -> Array3x3xN[Float]:
    arr.dtype                               # PyCharm does code completion!
    assert is_bearable(arr, Array3[Float])  # beartype will dynamically check this
    return arr                              # PyCharm and MyPy will NOT detect the issue with this
```

And... I'm sensing a new @beartype feature request here.

**Comment by baterflyrity** [comment] 2022-02-08 08:23
@ramonhagenaars , very nice! Also i would suggest adding some dynamic constructor/fabric to avoid auxiliary code. For example:
```python
def fun(arr: Array[3][Float]) -> Array[3, 3, Any][Float]:...
```
But unfortunately i cant predict whether static typer checkers can do so deep type inference. 

p.s.
Additionally i suppose to take into account `...` as an alternative to `Any`.

**Comment by ramonhagenaars** [comment] 2022-02-08 18:43
>  This is all fantabulous – except possibly that trailing proviso about helper functions. On the one hand, helper functions are helpful. That's good. On the other hand, static type checkers and IDEs are utterly incapable of understanding helper functions defined at runtime.

Yes, I was aware of this unfortunate lack of deeper insight of PyCharm/MyPy, so we're on the same page. I had something different in mind. Since in this little proposal, the variable name becomes the spindle of readability - I'm trying hard to get anywhere near your level of poetic writing - it should be chosen with care and consistency. Therefore, I thought it would be convenient to offer a function that can suggest a nice variable name for a given `Dim`:

```python
>>> suggest_name(Dim(3, 3, Any))
Array3x3xN
```

I think I could go one step further and enforce (with some of the blackest magic) the naming, as is similarly done with `TypeVar`. However, I'm a bit reluctant because of the dark forces that can be set loose by doing so. Such choices should be taken by a greater Council of Wizards and Gorillas.

> Alternatively, if you'd prefer to offload the work to https://github.com/beartype, beartype 0.10.0 introduces a similar is_bearable() function.

That is definitely something to consider, although I'm a bit hestitant to adding a dependencies for this little lib. But I do think it would be awesome to make nptyping bear-compatible. 💪🐻

**Comment by ramonhagenaars** [comment] 2022-02-08 18:51
@baterflyrity 

>  Also i would suggest adding some dynamic constructor/factory to avoid auxiliary code

That would be nice indeed, if it were not for MyPy and PyCharm (and other IDEs probably). By going any level deeper than the `Annotated` with e.g. a factory function or a class, MyPy and PyCharm won't work anymore. If one could care less about these tools, then the current `nptyping` style will do. Otherwise, concessions have to be made unfortunately. 🙁 

> Additionally i suppose to take into account ... as an alternative to Any.

The Ellipsis will have its place actually:
```python
Dim(3, ...)    # <-- this will denote multiple dimensions of size 3
Dim(Any, ...)  # <-- this will denote multiple dimensions of any size
```

**Comment by leycec** [comment] 2022-02-10 03:01
> ...although I'm a bit hestitant to adding a dependencies for this little lib.

**Absolutely.** We are on the same page... and that page reads: "Beware. Chest-thumping gorilla wizards tread here."

I suppose I was obliquely suggesting that `nptyping` might just declare `Dim` and related primitives while letting external type-checkers [insert @beartype here] handle the actual type-checking of those primitives. I kinda suspect most users would rather `nptyping` "just work" out-of-the-box rather than manually, repeatedly calling an `nptyping.is_instance_of()` tester to validate every NumPy array throughout a codebase.

Ideally, this should just work:

``` python
from beartype import beartype

# @beartype will now type-check both
# the "arr" parameter and return value here
# without anyone having to call anything.
@beartype
def fun(arr: Array3[Float]) -> Array3x3xN[Float]:
    arr.dtype                               # PyCharm does code completion!
    return arr                              # PyCharm and MyPy will NOT detect the issue with this
```

> But I do think it would be awesome to make `nptyping` bear-compatible. :muscle: :bear:

**Love the muscle bear.** Let's flex!

Also, yes. It'd be wondrous to add @beartype support for `nptyping`. From our glaucoma-clouded perspective, what we'd *love* is for `nptyping` to present a similar API to standard PEP-compliant type hints – which means the proposed magical unicorn `Dim` class should ideally:

* **Be subscriptable.** There are two ways to accomplish this; either:
  * Define the `__class_getitem__()` dunder method. Sadly, this requires Python ≥ 3.9. So, non-ideal.
  * Make `Dim` a singleton factory object defining the standard `__getitem__()` dunder method instead. This is how beartype validators are defined, if that helps. Your API might then resemble:

  ``` python
  Dim[3, 3, ...]
  ```

* **Be introspectable.** In either case, the objects produced by subscripting `Dim` should define the `__args__` instance variable to be a tuple of the 0 or more items originally subscripting `Dim`: e.g.,

  ``` python
  >>> Dim[3, 3, ...].__args__
  (3, 3, Ellipses)
  ```

*Aaaaaand...* that's all she wrote, because it's late and even the ghastly shade of Angela Lansbury is tired. :older_woman:  :book:

**Comment by ramonhagenaars** [comment] 2022-03-19 14:50
Hello there fellow type-check-craving folks!

Some time has passed since my last reply here, but not without good reason I believe. Because the brand new `nptyping2.0.0a1` is about to be released!

I found a way to keep `NDArray` an inline type hint, without requiring a separate `Annotated` line, while keeping MyPy and PyCharm happy.

The `NDArray` uses `typing.Protocol` in a `.pyi` file. If enough methods (at least 1) are added to that `Protocol`, MyPy will be able to statically check a variable to be an `NDArray`. At the same time, it allows PyCharm to know these methods and provide auto-completion.

This:
```python
Array3x3xN = Annotated[NDArray[T], Dim(3, 3, Any)]

def fun(arr: Array3x3xN[Float]): ...
```
Can now be written as this:
```python
def fun(arr: NDArray[Float, Shape["3, 3, *"]]): ...
``` 
This `2.0.0a` notation:
* is MyPy friendly: MyPy will correctly complain on any non ndarray;
* is IDE friendly: the code completion on an NDArray hinted variable works;
* allows for a lot of flexibility concerning the shape, such as variables, labels and more;
* allows for a similar approach for structured types;
* is beartype compatible out of the box. 🐻👍

So any drawbacks? Well... at least one. For a complete code-completion, the `NDArray` must exhaustively denote all methods and properties from `ndarray`. Believe me, I tried all kinds of trickery to reuse `numpy`'s type, but to no avail. So this will mean that I will need to spend a lot of evenings to supplement `NDArray` of methods. Copy-pasting and slightly adjusting the methods from `numpy.ndarray.pyi`... 😣 I will start with this after this first alpha release.

**Comment by leycec** [comment] 2022-03-19 23:17
**Wow.** Big congratulations on the API win, @ramonhagenaars! Typing bros unite for the common good of code completion. And might I add that this...

> The `NDArray` uses `typing.Protocol` in a `.pyi` file.

...is *extremely* clever. I never would have thought of that – but now I wish I would. I have only three questions, because you are the mega-mind in the room. Let's begin.

## What Can We Do for You?

Does this require any additional heavy lifting from runtime type checkers (*...so, @beartype is what I'm saying*) *or* will this just automatically work out-of-the-box with standard runtime checks (e.g., `isinstance(..., nptyping.NDArray[...])`) thanks to the structural subtyping magic of `typing.Protocol`?

I kinda suspect this "just works," but desperately want to double-check. If this does indeed "just work," I'll rapidly add a feature request at @beartype's issue tracker for us to document this.

Our userbase – most of whom are data scientists, machine learning savants, and natural language processing bros – will be *very* interested to find out about this.

## Synchronization with Upstream NumPy Changes

Synchronizing your type stubs with upstream changes to the NumPy API will probably be an ongoing background concern that annoys us all in the months and years to come. Have you given any thought to, say, a battery of unit or integration tests that explicitly warn you when your type stubs get desynchronized from upstream type stubs?

We recently [doctored up similar unit tests to ensure that our `beartype.typing` compatibility layer provides exactly the set of exported public attributes of the standard `typing` module](https://github.com/beartype/beartype/blob/main/beartype_test/a00_unit/test_typing.py). We're sure you're already on top of something hot like that, so... you've already got this on lockdown.

Yet again, so much hype for this! But we're not done yet. We never are when @leycec drunkenly crashes the Git party.

## There Are Many Tensor APIs

NumPy is the most popular tensor API. Yup. This is the case. But there's an increased proliferation of alternate tensor APIs like PyTorch and Google's TensorFlow and [JAX](https://github.com/google/jax). Almost all of them share at least the core properties of NumPy arrays – including:

* A `dtype`.
* A `shape`.
* A dimensionality (e.g., `ndim`).

Looking upward and onward beyond the immediate horizon line, it'd be the chef's kiss to slowly (yet confidently) generalize the API to cover these as well. In @beartype's case, our scientific audience is most hyped up about PyTorch and then JAX (in that order).

Food for future thought. It tastes delicious, bro. :kiwi_fruit: 

Thanks again for the all the tremendous volunteerism, @ramonhagenaars! :clap: :clap:

**Comment by ramonhagenaars** [comment] 2022-03-21 20:16
> Does this require any additional heavy lifting from runtime type checkers...?

Nope, it will work out of the box thanks to the regular `isinstance`! As a matter of fact, I already checked against `beartype` and it works like a charm(ing bear)!

This doesn't mean that it couldn't be improved though. Currently, instance checking is black or white, yes or no, `True` or `False`. I can imagine that for a little more complex shapes, it might be useful to also get a little more information on why the instance checking failed. These details could be set onto an Exception (which is subsequently wrapped into a `BeartypeException`). For this, I think `beartype` could propose a duck-contract - just made up that word - such as: "implement a method called `__compareinstance__` with this and this interface, that raises any exception that has attribute `instance`, `reasons`, ... ". Something like that.

> Synchronizing your type stubs with upstream changes to the NumPy API will probably be an ongoing background concern that annoys us all in the months and years to come.

Afraid so, yeah. :-( Although the "only" drawback is the uncomplete code completion here, I find that less of a problem than not being "MyPyable" and IDE friendly. But a bummer nonetheless; no free lunch for bears or gorillas... 🐻🦍

> Have you given any thought to, say, a battery of unit or integration tests that explicitly warn you when your type stubs get desynchronized from upstream type stubs?

I haven't. Well, now I have. I think that's a good idea! 😃 

> chef's kiss

Nice! Your reactions upgrade my vocabulary!

> generalize the API to cover these [other Tensor apis such as Tensorflow, Jax, etc.] as well 

It may take me some time, but I'd like to see that for `nptyping` also. The not so distant future (`2.1.0` I think), will bring (back) the structured array and `recarray`. From the api for these, I think a small step can be made to cover also `pandas.DataFrame`, which is on my personal wishlist. Tensorflow could be the next in line.

> Thanks again for the all the tremendous volunteerism

And thank you for `beartype`, your enthusiasm and ideas! It motivates me, highly appreciated!

**Comment by leycec** [comment] 2022-03-22 06:30
**QA intensifies.** This is typing nonpariel. Take all my thumbs. :+1: 

> As a matter of fact, I already checked against `beartype` and it works like a charm(ing bear)!

:love_you_gesture: 

Because *quid pro quo* is the only Latin I know, I've opened a [new issue at our tracker politely requesting that we document this in our existing FAQ entry on typing NumPy arrays](https://github.com/beartype/beartype/issues/115).

> I can imagine that for a little more complex shapes, it might be useful to also get a little more information on why the instance checking failed. These details could be set onto an `Exception` (which is subsequently wrapped into a `BeartypeException`). For this, I think `beartype` could propose a duck-contract - just made up that word - such as:

**Hotness personified.** This is the way, except this is *not* the way:

> implement a method called `__compareinstance__` with this and this interface, that raises any exception that has attribute instance, reasons, ...

Well, that's *almost* the way. But [Python explicitly reserves all dunder names (i.e., attributes whose names match `__*__`) for forward compatibility with itself](https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers):

> `__*__`
>
> System-defined names, informally known as “dunder” names. These names are defined by the interpreter and its implementation (including the standard library). Current system names are discussed in the [Special method names](https://docs.python.org/3/reference/datamodel.html#specialnames) section and elsewhere. More will likely be defined in future versions of Python. **Any use of __*__ names, in any context, that does not follow explicitly documented use, is subject to breakage without warning.**

Let's slowly back away from the flaming wreckage perched precariously on the edge of the chasm. Instead, how about an API resembling:

```python
# In the utopian dreamworld that is `nptyping`:
class NDArray(...):
    ...

    def is_instance_or_die(obj: object) -> None:
        '''
        Raise a human-readable exception describing the failure
        of the passed arbitrary object to satisfy this type hint if
        that object violates this hint *or* silently reduce to a noop.
        '''

        # Something, something, QA, something, something.
        if not isinstance(obj, self):
            raise NDException(
                f'Object {repr(obj)} violates '
                f'type hint nptyping.NDArray[self.__args__], because...'
                f'Look. Just because, alright?'
            )
```

**Typing in 2022:** it's gettin' hairy like :gorilla:.

**Comment by ramonhagenaars** [comment] 2022-03-27 18:25
> I've opened a new issue at our tracker politely requesting that we document this in our existing FAQ entry on typing NumPy arrays

That is awesome! Needless to say of course: you'd best wait until the actual `2.0.0` stable release.

By the way, `beartype` is now tested against and `2.0.0a2` shows an example of the combined strength: https://github.com/ramonhagenaars/nptyping/blob/ecc668350a4247e829b45c2fb38df1c957d60953/USERDOCS.md?plain=1#L397


> But Python explicitly reserves all dunder names ...

Good point that one. 👆 Your suggestion (`is_instance_or_die`) is better indeed. Should I maybe open an issue at `beartype`'s place to formalize this one?

---

And now for something completely different.

Release `2.0.0a2` is at hand. This may very well be the last stage before the actual `2.0.0` stable release.

So, what has changed?

* `2.0.0a2` is 100% in sync with `numpy.typing` and 100% of `ndarray`'s attributes are code-completed with `nptyping.NDArray` 🎉

As I progressed adding more attributes using the `Prototype` solution, I found that `MyPy` took longer and longer to finish type checking. At some point, it seemingly never stopped at all. Apparently, `Prototype`s can be very costly with `MyPy`. This forced me to check one more time for a better alternative, which I found. The simplicity of the [endresult](https://github.com/ramonhagenaars/nptyping/blob/ecc668350a4247e829b45c2fb38df1c957d60953/nptyping/ndarray.pyi#L27) fills me with joy, but simultaneously makes me feel like a 🐒 for not finding it sooner.

* Breaking change since `2.0.0a1`: it is now `NDArray[<shape>, <dtype>]` instead of `NDArray[<dtype>, <shape>]`;

This was enforced to make the former bullet point possible. It's probably better to stick close to `numpy` anyway.

**Comment by leycec** [comment] 2022-03-29 19:00
When our powers combine, we type NumPy arrays – *whether they want to be typed or not.*

> By the way, `beartype` is now tested against and 2.0.0a2 shows an example of the combined strength...

Thanks so much for the kind name drop! *Quid pro quo* now demands I do something for you, too. Sadly, our documentation is in disarray and I'm currently in the throes of beating Sphinx about the ankles with a burlap sack. I've had better Wednesdays.

> Should I maybe open an issue at beartype's place to formalize this one?

**Excellent suggestion.** You've already done so much for typing kind, so [I've got this one](https://github.com/beartype/beartype/issues/116). As soon as Sphinx has been forcibly subdued and `nptyping 2.0.0` drops, I'll be over this one like a bear on a honeypot.

> The simplicity of the [endresult](https://github.com/ramonhagenaars/nptyping/blob/ecc668350a4247e829b45c2fb38df1c957d60953/nptyping/ndarray.pyi#L27) fills me with joy...

```python
NDArray = np.ndarray
```

:open_mouth: 

Literally cannot believe that works. But then... I'm literally bald and on the cusp of malding at Sphinx `autodoc` for its repeated failures against all humanity.

![me. today.](https://linguaholic.com/linguablog/wp-content/uploads/2020/08/The-Meaning-of-Malding-on-Twitch.png.webp)

**Comment by leycec** [comment] 2022-03-30 05:27
**Addendum:** As noted at beartype/beartype#116, @beartype would be best pleased with an `nptyping` getter method returning a sentence fragment describing the cause of the failure (rather than raising an exception, which requires possibly fragile string munging and is thus less ideal for us all): e.g.,

```python
# In the utopian dreamworld that is `nptyping`:
class NDArraySubscripted(...):
    '''
    Object produced by subscripting (indexing) :class:`NDArray`.
    '''

    def get_cause(array: object) -> Optional[str]:
        '''
        Get a sentence fragment describing the failure
        of the passed arbitrary object to satisfy this type hint if
        that object violates this hint *or* just return ``None``.
        '''

        # If this object satisfies this hint, return "None".
        if isinstance(array, self):
            return None
        # Else, this object violates this hint.

        # Let's pretend the shape is the problem.
        return (
            f'NumPy array {repr(array)} shape '
            f'{repr(array.shape)} != {repr(self.shape)}'
        )
```

Apex ~~predators~~ typers unite! :gorilla: + :bear: = :+1:

**Comment by ramonhagenaars** [comment] 2022-04-07 18:48
Version `2.0.0` is about to be released and with that, this ticket will be closed. Thanks for the discussion here guys! 👍

**Closed** 2022-04-07 18:53 UTC
Labels: help wanted, feature
